-define(INVALID_JSON   , {1,  <<"invalid json">>}).
-define(PUSH_BUSY      , {2,  <<"messaging system busy">>}).
-define(PUSH_NOMESSAGE , {3,  <<"no message for push command">>}).
-define(PUSH_NOCHANNEL , {4,  <<"no channel for push command">>}).
-define(JSON_BADCOMMAND, {5,  <<"bad command syntax">>}).
-define(UNKNOWN_ERROR  , {6,  <<"unknown error">>}).
-define(AUTH_REQUIRED  , {7,  <<"authentication required">>}).
-define(AUTH_NOLOGIN   , {8,  <<"unknown error">>}).
-define(AUTH_NOPASSWORD, {9,  <<"authentication required">>}).
-define(AUTH_FAILED    , {10, <<"authentication failed">>}).
-define(BADCOMMAND     , {11, <<"bad command">>}).
-define(BADEMAIL       , {12, <<"bad email address">>}).
-define(BADLOGINTYPE   , {13, <<"bad login type">>}).
-define(BADSYSACCOUNT  , {14, <<"bad system account id">>}).
-define(NODEVKEY       , {15, <<"no development key">>}).
-define(LOGININUSE     , {16, <<"login already in use">>}).
-define(BADPROFILE     , {17, <<"bad profile">>}).
-define(UNKNOWNCOMMAND , {18, <<"unknown command">>}).
-define(NODEVICEID     , {19, <<"bad profile">>}).
-define(BADDEVICETYPE  , {20, <<"unknown command">>}).
