			<div id="sidebar">
				<ul>
					<li id="search">
						<h3>Search</h3>
						<form id="searchform" method="get" action="">
							<div>
								<input type="text" name="s" id="s" size="15" />
								<br />
								<input name="submit" type="submit" value="Go" />
							</div>
						</form>
					</li>
					<!--li>
						<h3>Veroeros etiam</h3>
						<p><strong>Morbi sit amet</strong> mauris Nam vitae nibh eu sapien dictum pharetra. Vestibulum elementum neque vel lacus. Proin auctor dolor loremmassa. Phasellus sit. <a href="#">More&hellip;</a></p>
					</li-->
					<li>
						<h3>Server description</h3>
						<ul>
							<li><a target="_blank" href="https://github.com/mijkenator/mijkweb/blob/master/mysql.sql">
                                         Database structure</a></li>
							<li><a href="#">Session structure</a></li>
							<li><a href="#">Nginx server configuration</a></li>
							<li><a href="#">Cache server</a></li>
							<li><a href="#">CLientside javascript</a></li>
							<li><a href="#">Erlang backend</a></li>
							<li><a href="#">Comet mechanism</a></li>
							<li><a href="#">Tsung testing</a></li>
							<li><a href="#">Test results</a></li>
						</ul>
					</li>
				</ul>
			</div>
			<!-- end #sidebar -->
			<div style="clear: both;">&nbsp;</div>
			<div id="widebar">
				<div id="colA">
					<h3>Recent posts</h3>
					<dl class="list1">
						<dt>12.17.2007</dt>
						<dd><a href="#">Praesent nonummy sed lorem</a></dd>
						<dt>12.13.2007</dt>
						<dd><a href="#">Mauris sagittis neque nec nisi sed</a></dd>
						<dt>12.05.2007</dt>
						<dd><a href="#">Vel turpis integer leo venenatis</a></dd>
						<dt>12.02.2007</dt>
						<dd><a href="#">Et pharetra quis sed viverra ante</a></dd>
						<dt>11.30.2007</dt>
						<dd><a href="#">Integer leo lorem sed lorem</a></dd>
					</dl>
				</div>
				<div id="colB">
					<h3>Pharetra Sed Tempus</h3>
					<p>Morbi sit amet mauris Nam vitae nibh eu sapien dictum pharetra. Vestibulum elementum neque vel lacus. Lorem ipsum dolor sit dolore phasellus pede lorem proin auctor dolor loremmassa phasellus sit. <a href="#">More&hellip;</a></p>
				</div>
				<div id="colC">
					<h3>Donec Lorem Interdum</h3>
					<ul class="list2">
						<li><a href="#"><img src="images/img12.jpg" alt="" width="50" height="50" /></a></li>
						<li><a href="#"><img src="images/img13.jpg" alt="" width="50" height="50" /></a></li>
						<li class="nopad"><a href="#"><img src="images/img14.jpg" alt="" width="50" height="50" /></a></li>
						<li><a href="#"><img src="images/img15.jpg" alt="" width="50" height="50" /></a></li>
						<li><a href="#"><img src="images/img16.jpg" alt="" width="50" height="50" /></a></li>
						<li class="nopad"><a href="#"><img src="images/img17.jpg" alt="" width="50" height="50" /></a></li>
					</ul>
				</div>
				<div style="clear: both;">&nbsp;</div>
			</div>
			<!-- end #widebar -->
		</div>
		<!-- end #page -->
	</div>
	<!-- end #wrapper2 -->
	<div id="footer">
		<p>(c) 2012 mijkenator .</p>
	</div>
</div>
<!-- end #wrapper -->
</body>
</html>
