<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>mijkenators website</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="/css/main.css" rel="stylesheet" type="text/css" media="screen" />
</head>
<body>
<div id="wrapper">
	<div id="wrapper2">
		<div id="header">
			<div id="logo">
				<h1>.......</h1>
			</div>
			<div id="menu">
				<ul>
					<li><a href="#">Homepage</a></li>
					<li><a href="/login/">Demo</a></li>
					<li><a href="#">Links</a></li>
					<li><a href="#">CV</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
			</div>
		</div>
		<!-- end #header -->
